## AAA 패턴

> 준비(Arrange)-실행(Act)-검증(Assert)
> 
- **준비 : 테스트에 필요한 변수나 함수를 초기화**
- **실행 : 준비단계에서 설정한 것으로 결과를 만들어냄**
- **검증 : 만들어낸 결과가 예상과 일치하는지 확인**

## 검증 메소드 ( 문자열 비교 )

> 테스트 코드는 동일한 비즈니스 로직에서 항상 같은 결과를 보장해야 하기에 테스트의 유지 보수성과 불안전성을 줄이는 것을 우선시해야한다.
> 

단순히 문자열 일치를 판단하면 유지 보수성이 떨어진다.

아래의 정규 표현식을 사용하는 두 메서드를 사용하면 나중에 테스트 대상 코드가 변경되어도 실패할 가능성 줄일 수 있다.

**`expect(value).toMatch(/string/)` : 정규 표현식 혹은 문자열 패턴과 매칭되는지 검사**

ex ) `expect('error fake reason').toMatch('fake reason')` → 통과

**`expect(value).toContain('string')` : 단순히 부분 문자열 포함되어 있는지 검사**

ex ) `expect('error fake reason').toContain('fake reason')` → 통과

## USE 전략

> 테스트 코드 이름 짓는 방법
> 

테스트 이름 지을 때 고려해야할 세가지 주요 요소

- **테스트하려는 대상(Unit)**
- **입력 값이나 상황에 대한 설명 (Senario)**
- **기댓값이나 결과에 대한 설명 (Expectation)**

**예시**

**`test(’verifyPassword, given a failing rule, returns errors’)`**

- **Unit** : verifyPassword
- **Senario** : given a failing rule
- **Expectation** : returns errors

## USE 전략 + describe() 함수로 구역 나누기

### 구역 나눠보기

**`describe()` 함수는 테스트 그룹을 만드는 함수이다.**

- 그룹을 설정하면 들여쓰기가 적용되기 때문에 가독성 높일 수 있음.
- 테스트 코드 구조를 좀 더 체계적으로 나누고 관리할 수 있다. ( USE 전략의 세 가지 요소 분리 가능 )

```tsx
// decribe 전략을 사용한 이름 짓기
describe('verifyPassword', () => {
    test('given a failing rule, returns errors', () => {
        const fakeRule: ValidationRule = (input) => ({
            passed: false,
            reason: 'fake reason'
        })
        const errors = verifyPassword('any value', [fakeRule])
        expect(errors[0]).toContain('fake reason')
    })
});

// describe 중첩 사용
describe('verifyPassword', () => {
    describe('given a failing rule', () => {
        test('returns errors', () => {  
            const fakeRule: ValidationRule = (input) => ({
                passed: false,
                reason: 'fake reason'
            })

            const errors = verifyPassword('any value', [fakeRule])
            
            expect(errors[0]).toContain('fake reason')
        })
    })
})

```

![중첩을 사용하면 위 결과처럼 ‘>’로 depth가 구분된다.](attachment:f89490af-3033-49e9-8643-0ec696cab085:image.png)

중첩을 사용하면 위 결과처럼 ‘>’로 depth가 구분된다.

### describe - it

test() 메소드 대신에 it() 메소드 사용할 수 있다.

- **`test` 는 테스트 대상과 테스트 상황이 명확할 때 쓰면 좋을 듯**
- **`describe - it` 은 동일한 시나리오에서 동일한 진입점에 대해 여러 결과를 검증할 때 ( 복잡.. 계층 구조가 필요할 때 ) → 행동 주도 개발 스타일**

테스트 복잡성과 표현의 필요성에 따라 적절한 방식을 선택하면 된다.

## 검증 룰렛

### 문제

테스트 코드에서 검증(assertion) 구문이 명확하지 않거나 너무 많아 테스트 실패 시 어떤 원인으로 실패했는지 파악하기 어려운 상황

```tsx
describe('PasswordVerifier', () => {
    describe('with a failing rule', () => {
        it('has an error message based on the rule.reason', () => {
            const verifier = new PasswordVerifier1();
            const fakeRule: ValidationRule = (input) => ({
                passed: false,
                reason: 'fake reason'
            })

            verifier.addRule(fakeRule); // 유효성 검사 룰 추가
            const errors = verifier.verify('any value'); // 추가된 룰들로 유효성 체크하는 verify() 호출
            expect(errors[0]).toContain('fake reason');
        })
    })
})
```

위 예시에서 addRule()과 verify()는 테스트 시에 **결합(coupling)**되어서 **함께 실행**되어야한다. ( PasswordVerifier1 내부 상태를 노출하지 않고 테스트 하려면.. )

하지만 동일한 시나리오에서 여러 테스트를 작성하고 싶다면? ( 종료점이 여러 개이거나 동일한 종료점에서 여러 값을 테스트하고자 할 경우 )

```tsx
verifier.addRule(fakeR∪le) ；
const errors = verifier.verify('any value')；
expect(errors.length).toBe(1)；// 검증 코드를 하나 추가했다.
expect(errors［이).toCo∩tai∩(,fake reason')；
```

위 경우  첫번째 검증이 실패하면 테스트가 실패 처리되고 다음 테스트로 이동하기 때문에 두번째 테스트코드는 실행되지 않는다.

이렇게 한 테스트(시나리오)에 여러 검증이 존재할 경우 우선적인 검증 실패가 먼저 처리되기 때문에 뒷 부분의 검증이 어떻게 될지 파악할 수 없다.

### 해결..?

```tsx
describe('PasswordVerifier', () => {
    describe('with a failing rule', () => {
        it('has an error message based on the rule.reason', () => {
            const verifier = new PasswordVerifier1();
            const fakeRule: ValidationRule = (input) => ({
                passed: false,
                reason: 'fake reason'
            })

            verifier.addRule(fakeRule);
            const errors = verifier.verify('any value');
            expect(errors[0]).toContain('fake reason');
        })

        it('has exactly one error', () => {
            const verifier = new PasswordVerifier1();
            const fakeRule: ValidationRule = (input) => ({
                passed: false,
                reason: 'fake reason'
            })

            verifier.addRule(fakeRule);
            const errors = verifier.verify('any value');
            
            expect(errors.length).toBe(1);
        })
    })
})
```

추가 검증 코드를 별도의 테스트 케이스로 분리하고, 이해하기 쉬운 이름을 붙였다.

근데, 이렇게 하니 준비(Arrange) 구문이 중복되는 것을 볼 수 있다.

## ⭐ beforeEach() 함수를 활용하여 준비(Arrange) 구문 중복 줄이기

**`beforeEach()` 함수는 각 테스트 케이스가 실행되기 전에 한 번씩 실행되는 함수**이다.

```tsx
describe('PasswordVerifier', () => {
    let verifier: PasswordVerifier1;

    beforeEach(() => { // beforeEach-A
        verifier = new PasswordVerifier1();
    })

    describe('with a failing rule', () => {
        let fakeRule: ValidationRule;
        let errors: string[];
        
        beforeEach(() => { // beforeEach-B
            fakeRule = (input) => ({
                passed: false,
                reason: 'fake reason'
            })

            verifier.addRule(fakeRule);
        });

        it('has an error message based on the rule.reason', () => {
            errors = verifier.verify('any value');
            expect(errors[0]).toContain('fake reason');
        })

        it('has exactly one error', () => {
            errors = verifier.verify('any value');
            expect(errors.length).toBe(1);
        })
    })
})
```

⚠️ **각 테스트 케이스라는건 it() 혹은 test()를 말한다.**

- `has an error message based on the rule.reason` 검증 실행할 때 [beforeEach-A] → [beforeEach-B] → it()
- `has exactly one error` 검증 실행할 때 [beforeEach-A] → [beforeEach-B] → it()
- 난 제일 처음에 있는 [beforeEach-A]는 describe 상위에 있기 때문에 한번만 수행할 줄 알았는데 it() 마다 따로 수행을 하네.

⚠️ **중복은 줄었지만 여전한 문제..!**

- beforeEach-B에서 errors 배열을 초기화하는 로직이 없다. → 사이드 이펙트 발생 가능성 있음.
- **jest는 기본적으로 단위 테스트를 병렬 수행** → verifier 변수는 테스트가 공유하는데, 병렬로 수행하는 과정에서 이 변수의 상태를 임의로 변경 가능 (잠재적 문제)

### beforeEach()에 대한 스크롤 피로감..!

위 코드를 보았을 때 중복은 줄었지만 단점이 생겼다.

- **`it()`** 검증 구문만 봐서는 **`verifier`**가 어디에서 만들어졌는지 모른다. → 스크롤 위로 올려서 확인해봐야함.
- **`addRule()`**을 **`it()`** 검증 구문 밖에서 수행했기 때문에 어떤 룰이 추가되었는지 모른다. → 스크롤 위로 올려서 확인해봐야함.

스크롤 피로감이라고 말했지만, 결국 테스트 파일을 이해하기 어려워서 유지 관리하는 일이 번거로운 작업이 될 수 있다는 것.

```tsx
// 스크롤 피로감을 줄이기 위한 첫시도
describe('PasswordVerifier', () => {
    let verifier: PasswordVerifier1;

    beforeEach(() => {
        verifier = new PasswordVerifier1();
    })

    describe('with a failing rule', () => {
        let fakeRule: ValidationRule;
        let errors: string[];
        
        beforeEach(() => {
            fakeRule = (input) => ({
                passed: false,
                reason: 'fake reason'
            })
            verifier.addRule(fakeRule);
            errors = verifier.verify('any value'); // 공통된 act 구문이 각 테스트케이스(it)에서 beforeEach로 옮겨졌다.
        });

        it('has an error message based on the rule.reason', () => { 
            expect(errors[0]).toContain('fake reason');
        })

        it('has exactly one error', () => {
            expect(errors.length).toBe(1);
        })
    })
})
```

beforeEach()에 준비(Arrange)구문, 실행(Act)구문을 몰아넣었다.

이렇게 하니, 준비 구문과 실행 구문을 왔다갔다 스크롤 할 필요 없이 beforeEach() 안에서 다 볼 수 있게 되었다.

```tsx
// 테스트 시나리오 추가해서 테스트 케이스 늘어났을 때도 확장 가능한 구조인지 확인하기
describe('PasswordVerifier', () => {
    let verifier: PasswordVerifier1;

    beforeEach(() => {
        verifier = new PasswordVerifier1();
    })

    describe('with a failing rule', () => {
        let fakeRule: ValidationRule;
        let errors: string[];
        
        beforeEach(() => {
            fakeRule = (input) => ({
                passed: false,
                reason: 'fake reason'
            })
            verifier.addRule(fakeRule);
            errors = verifier.verify('any value');
        });

        it('has an error message based on the rule.reason', () => { 
            expect(errors[0]).toContain('fake reason');
        })

        it('has exactly one error', () => {
            expect(errors.length).toBe(1);
        })
    })

    describe('with a passing rule', () => {
        let fakeRule: ValidationRule;
        let errors: string[];
        
        beforeEach(() => {
            fakeRule = (input) => ({
                passed: true,
                reason: ''
            })
            verifier.addRule(fakeRule);
            errors = verifier.verify('any value');
        })

        it('has no errors', () => {
            expect(errors.length).toBe(0);
        })
    })

    describe('with a failing and a passing rule', () => {
        let fakeRulePass: ValidationRule;
        let fakeRuleFail: ValidationRule;
        let errors: string[];

        beforeEach(() => {
            fakeRulePass = (input) => ({
                passed: true,
                reason: ''
            })
            fakeRuleFail = (input) => ({
                passed: false,
                reason: 'fake reason'
            })

            verifier.addRule(fakeRulePass);
            verifier.addRule(fakeRuleFail);
            errors = verifier.verify('any value');
        })

        it('has one error', () => {
            expect(errors.length).toBe(1);
        })

        it('error text belongs to failed rule', () => {
            expect(errors[0]).toContain('fake reason');
        })
    })
})
```

시나리오를 좀 더 확장해보니 문제가 또 보인다.

- beforeEach() 내에 또 중복 코드가 생겼다. ( 각 시나리오마다 )
- beforeEach()가 어떤 it() 함수와 연관이 있는지 확인해봐야한다 → 스크롤 피로.. → 복잡!

**책의 저자는 beforeEach() 함수를 사용하는 방식을 별로 안좋아한다고 함.**

**→ beforeEach()가 일종의 쓰레기통으로 전락하여 온갖 것들을 다 집어 넣기 쉽기 때문이다!**

## beforeEach() 말고 팩토리 함수를 만들어서 개선해보기

### 1단계. beforeEach()에 있던 공통의 로직을 함수로 분리하여 외부로 빼보기

```tsx
// 팩토리 함수 사용해보기
describe('PasswordVerifier', () => {
    let verifier: PasswordVerifier1;

    beforeEach(() => {
        verifier = new PasswordVerifier1();
    })

    describe('with a failing rule', () => {
        let fakeRule: ValidationRule;
        let errors: string[];
        
        beforeEach(() => {
            fakeRule = makeFailingRule('fake reason');
            verifier.addRule(fakeRule);
            errors = verifier.verify('any value');
        });

        it('has an error message based on the rule.reason', () => { 
            expect(errors[0]).toContain('fake reason');
        })

        it('has exactly one error', () => {
            expect(errors.length).toBe(1);
        })
    })

    describe('with a passing rule', () => {
        let fakeRule: ValidationRule;
        let errors: string[];
        
        beforeEach(() => {
            fakeRule = makePassingRule();
            verifier.addRule(fakeRule);
            errors = verifier.verify('any value');
        })

        it('has no errors', () => {
            expect(errors.length).toBe(0);
        })
    })

    describe('with a failing and a passing rule', () => {
        let fakeRulePass: ValidationRule;
        let fakeRuleFail: ValidationRule;
        let errors: string[];

        beforeEach(() => {
            fakeRulePass = makePassingRule();
            fakeRuleFail = makeFailingRule('fake reason');

            verifier.addRule(fakeRulePass);
            verifier.addRule(fakeRuleFail);
            errors = verifier.verify('any value');
        })

        it('has one error', () => {
            expect(errors.length).toBe(1);
        })

        it('error text belongs to failed rule', () => {
            expect(errors[0]).toContain('fake reason');
        })
    })

    const makeFailingRule = (reason: string): ValidationRule => {
        return (input: string) => ({
            passed: false,
            reason: reason
        })
    };

    const makePassingRule = (): ValidationRule => {
        return (input: string) => ({
            passed: true,
            reason: ''
        })
    };
    
})
```

일단, 첫번째로 fakeFailingRule()과 makePassingRule()을 만들어서 beforeEach마다 공통으로 존재하던 rule 만드는 로직을 분리하였다.

### 2단계. beforeEach() 함수를 완전히 대체해보기

```tsx
// 팩토리 함수 사용해보기 (beforeEach 완전 대체)
const makeVerifier = () => new PasswordVerifier1();
const passingRule = () => ({
    passed: true,
    reason: ''
});

const makeVerifierWithPadssingRule = () => {
    const verifier = makeVerifier();
    verifier.addRule(passingRule);
    return verifier;
};
const makeVerifierWithFailingRule = (reason: string) => {
    const verifier = makeVerifier();
    const fakeRule = () => ({
        passed: false,
        reason: reason
    })
    verifier.addRule(fakeRule);
    return verifier;
};

describe('PasswordVerifier', () => {
    describe('with a failing rule', () => {
        it('has an error message based on the rule.reason', () => { 
            const verifier = makeVerifierWithFailingRule('fake reason');
            const errors = verifier.verify('any value');
            expect(errors[0]).toContain('fake reason');
        })

        it('has exactly one error', () => {
            const verifier = makeVerifierWithFailingRule('fake reason');
            const errors = verifier.verify('any value');
            expect(errors.length).toBe(1);
        })
    })

    describe('with a passing rule', () => {
        it('has no errors', () => {
            const verifier = makeVerifierWithPadssingRule();
            const errors = verifier.verify('any value');
            expect(errors.length).toBe(0);
        })
    })

    describe('with a failing and a passing rule', () => {
        it('has one error', () => {
            const verifier = makeVerifierWithFailingRule('fake reason');
            verifier.addRule(passingRule);
            const errors = verifier.verify('any value');
            expect(errors.length).toBe(1);
        })

        it('error text belongs to failed rule', () => {
            const verifier = makeVerifierWithFailingRule('fake reason');
            verifier.addRule(passingRule);
            const errors = verifier.verify('any value');
            expect(errors[0]).toContain('fake reason');
        })
    })
})
```

중복을 제거하기 위해 beforeEach()를 사용해왔지만, 이번에는 공통된 로직을 팩토리함수로 만들어 외부로 분리하였다.

테스트할 때 이 팩토리 함수를 활용했는데, 이렇게 함으로써 코드 가독성이 더 올라갔다. ( it 함수 내에서 모든 정보를 파악할 수 있게 되었다 → 객체가 언제 생성되고 어떤 중요한 매개변수로 초기화되는지! )

beforeEach()를 없앴기 때문에 각 it() 함수는 필요한 설정을 자체적으로 처리하므로 다른 테스트와 상호 작용 없이 독립적으로 수행될 수 있다.

### 3단계. describe() 쓰지 않고 다시 test()로 바꿔보기

각 테스트를 보면 공유하는 값이 없고 각각 독립적으로 테스트가 가능하다.

AAA(준비, 실행, 검증)의 각 구문이 한 테스트 내에서 정의가 가능한 것으로 보이는데, 굳이 describe()로 테스트를 그룹화해야할까?

```tsx
const makeVerifier = () => new PasswordVerifier1();
const passingRule = () => ({
    passed: true,
    reason: ''
});

const makeVerifierWithPadssingRule = () => {
    const verifier = makeVerifier();
    verifier.addRule(passingRule);
    return verifier;
};
const makeVerifierWithFailingRule = (reason: string) => {
    const verifier = makeVerifier();
    const fakeRule = () => ({
        passed: false,
        reason: reason
    })
    verifier.addRule(fakeRule);
    return verifier;
};

test('pass verifier, with failed rule, has an error message based on the rule.reason', () => {
    const verifier = makeVerifierWithFailingRule('fake reason');
    const errors = verifier.verify('any value');
    expect(errors[0]).toContain('fake reason');
})

test('pass verifier, with failed rule, has exactly one error', () => {
    const verifier = makeVerifierWithFailingRule('fake reason');
    const errors = verifier.verify('any value');
    expect(errors.length).toBe(1);
})

test('pass verifier, with passing rule, has no errors', () => {
    const verifier = makeVerifierWithPadssingRule();
    const errors = verifier.verify('any value');
    expect(errors.length).toBe(0);
})

test('pass verifier, with failing and a passing rule, has one error', () => {
    const verifier = makeVerifierWithFailingRule('fake reason');
    verifier.addRule(passingRule);
    const errors = verifier.verify('any value');
    expect(errors.length).toBe(1);
})

test('pass verifier, with failing and a passing rule, error text belongs to failed rule', () => {
    const verifier = makeVerifierWithFailingRule('fake reason');
    verifier.addRule(passingRule);
    const errors = verifier.verify('any value');
    expect(errors[0]).toContain('fake reason');
})
```

describe()를 쓰지 않아 구조적인 명확성이 떨어질 것 같았으나, AAA 패턴이 여전히 잘 유지되어 각 테스트의 명확성을 유지할 수 있었다.

test()로 간결하게 써도 되고, describe()로 구조화할 수 있는데, 유지 보수성과 가독성의 균형을 찾아서 적절한 방법을 사용하도록 하자.

## 검증 메소드 ( 동등 비교 )

**`expect(targetValue).toEqual(expectedValue)` : targetValue와 expectedValue가 똑같은지 확인**

## test.each() / it.each()를 활용한 중복 없애기

### 문제상황

oneUpperCaseRule은 대문자가 하나이상 있는지 체크하는 규칙이다.

```tsx
describe('oneUpperCaseRule', () => {
    it('given no uppercase, it fails', () => {
        const result = oneUpperCaseRule('abc');
        expect(result.passed).toEqual(false);
    });

    it('given one uppercase, it passes', () => {
        const result = oneUpperCaseRule('Abc');
        expect(result.passed).toEqual(true);
    });

    it('given multiple uppercase, it passes', () => {
        const result = oneUpperCaseRule('aBC');
        expect(result.passed).toEqual(true);
    });
}); 
```

위 테스트를 보면 oneUpperCaseRule()의 인자로 문자열만 달리 넣는 것을 확인할 수 있으며, 그 외 로직에서 중복이 발생하는 것을 볼 수 있다.

### 해결1. 입력값 넣을 때 중복 로직 없애기

```tsx
describe('oneUpperCaseRule', () => {
    test('given no uppercase, it fails', () => {
        const result = oneUpperCaseRule('abc');
        expect(result.passed).toEqual(false);
    });

    test.each(['Abc', 'aBC'])('given one uppercase, it passes', (input) => {
        const result = oneUpperCaseRule(input);
        expect(result.passed).toEqual(true);
    });
}); 
```

oneUpperCaseRule의 입력값을 배열 순회를 돌면서 넣을 수 있게 해주었다.

### 해결2. 입력값과 검증 기댓값에 대한 중복 로직 없애기

```tsx
describe('oneUpperCaseRule', () => {
    test.each([
        ['Abc', true],
        ['aBC', true],
        ['abc', false],
    ])('given %s, it %s', (input, expected) => {
        const result = oneUpperCaseRule(input);
        expect(result.passed).toEqual(expected);
    });
}); 

```

test.each()의 인자로 들어가는 배열이 일차원 배열이면 input 값들로만 이루어진 배열이다.

이차원 배열이면 두번째 열에 해당하는 값은 테스트의 기댓값이다.

⚠️ 이건 test.each()에 묶는게 얼마나 쉬운지 보여주기 위한 예시.

- 이 테스트는 사실상 두 가지 다른 시나리오를 테스트하고 있다 - 대문자 없는 경우 / 대문자 하나 이상 있는 경우
- 서로 다른 테스트 두개로 분리하는 것이 낫다.

### 해결3. 제스트는 도구일뿐, 직접 순회 구현해서 테스트해보기

```tsx
describe('oneUpperCaseRule', () => {
    const tests = {
        'Abc': true,
        'aBC': true,
        'abc': false,
    }

    for (const [input, expected] of Object.entries(tests)) {
        test(`given ${input}, it ${expected}`, () => {
            const result = oneUpperCaseRule(input);
            expect(result.passed).toEqual(expected);
        });
    }
}); 
```

## 오류를 발생시키는 코드를 테스트하는 방법 - expect().toThrowError()

```tsx
// ..생략..
verify(input: string) {
    if (this.rules.length === 0) {
        throw new Error('There are no rules configured');
    }
    // ..생략..
}
```

위 코드를 테스트해보겠다고 하자. 등록된 rule이 없으면 에러를 발생시킨다.

이런 상황에서 제스트에서 제공하는 **`expect().toThrowError()`**를 활용해볼 수 있다.

```tsx
test('verify, with no rules, throws exception', () => {
    const verifier = makeVerifier();
    expect(() => verifier.verify('any value')).toThrow(/no rules configured/);
})
```

**`expect()`** 내부에서 에러가 발생했을 때, **`.toThrow()`**에서 어떤 에러가 발생했는지 잡아서 확인할 수 있다.

**`expect(value).toThrow(/string/)` : 정규 표현식 혹은 문자열 패턴과 에러 메세지가 매칭되는지 검사**

ex ) `expect(() => throw new Error('There are no rules configured') ).toThrow(/no rules configured/)` → 통과